# Site Settings
title: Test
email: email@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/test"
url: ""
twitter_username:
github_username:
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM